In [16]:
import numpy as np
import pandas as pd

In [8]:
apl16 = np.loadtxt('AAPL-2016.csv',delimiter=",", dtype=str)
apl17 = np.loadtxt('AAPL-2017.csv',delimiter=",", dtype=str)

In [106]:
print(apl16)

[['Date' 'Open' 'High' ... 'Close' 'Adj Close' 'Volume']
 ['2016-01-04' '102.610001' '105.370003' ... '105.349998' '100.274513'
  '67649400']
 ['2016-01-05' '105.750000' '105.849998' ... '102.709999' '97.761681'
  '55791000']
 ...
 ['2016-12-23' '115.589996' '116.519997' ... '116.519997' '113.373917'
  '14249500']
 ['2016-12-27' '116.519997' '117.800003' ... '117.260002' '114.093948'
  '18296900']
 ['2016-12-28' '117.519997' '118.019997' ... '116.760002' '113.607445'
  '20905900']]

In [65]:
df_2016 = pd.read_csv('AAPL-2016.csv')
df_2016

,Date,Open,High,Low,Close,Adj Close,Volume
0,2016-01-04,102.610001,105.370003,102.000000,105.349998,100.274513,67649400
1,2016-01-05,105.750000,105.849998,102.410004,102.709999,97.761681,55791000
2,2016-01-06,100.559998,102.370003,99.870003,100.699997,95.848511,68457400
3,2016-01-07,98.680000,100.129997,96.430000,96.449997,91.803276,81094400
4,2016-01-08,98.550003,99.110001,96.760002,96.959999,92.288696,70798000
...,...,...,...,...,...,...,...
245,2016-12-21,116.800003,117.400002,116.779999,117.059998,113.899338,23783200
246,2016-12-22,116.349998,116.510002,115.639999,116.290001,113.150139,26085900
247,2016-12-23,115.589996,116.519997,115.589996,116.519997,113.373917,14249500
248,2016-12-27,116.519997,117.800003,116.489998,117.260002,114.093948,18296900
249,2016-12-28,117.519997,118.019997,116.199997,116.760002,113.607445,20905900

In [103]:
df_2017 = pd.read_csv('AAPL-2017.csv')
df_2017

,Date,Open,High,Low,Close,Adj Close,Volume
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,113.013916,28781900
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,112.887413,21118100
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,113.461502,22193600
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,114.726402,31751900
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,115.777237,33561900
...,...,...,...,...,...,...,...
246,2017-12-22,174.679993,175.419998,174.500000,175.009995,173.023026,16114600
247,2017-12-26,170.800003,171.470001,169.679993,170.570007,168.633423,33185500
248,2017-12-27,170.100006,170.779999,169.710007,170.600006,168.663101,21498200
249,2017-12-28,171.000000,171.850006,170.479996,171.080002,169.137650,16480200
250,2017-12-29,170.520004,170.589996,169.220001,169.229996,167.308640,25884400

In [107]:
sliced_2016 = df_2016.iloc[0:50]
sliced_2016

,Date,Open,High,Low,Close,Adj Close,Volume
0,2016-01-04,102.610001,105.370003,102.000000,105.349998,100.274513,67649400
1,2016-01-05,105.750000,105.849998,102.410004,102.709999,97.761681,55791000
2,2016-01-06,100.559998,102.370003,99.870003,100.699997,95.848511,68457400
3,2016-01-07,98.680000,100.129997,96.430000,96.449997,91.803276,81094400
4,2016-01-08,98.550003,99.110001,96.760002,96.959999,92.288696,70798000
5,2016-01-11,98.970001,99.059998,97.339996,98.529999,93.783073,49739400
6,2016-01-12,100.550003,100.690002,98.839996,99.959999,95.144165,49154200
7,2016-01-13,100.320000,101.190002,97.300003,97.389999,92.697990,62439600
8,2016-01-14,97.959999,100.480003,95.739998,99.519997,94.725372,63170100
9,2016-01-15,96.199997,97.709999,95.360001,97.129997,92.450516,79010000
10,2016-01-19,98.410004,98.650002,95.500000,96.660004,92.003166,53087700
11,2016-01-20,95.099998,98.190002,93.419998,96.790001,92.126900,72334400
12,2016-01-21,97.059998,97.879997,94.940002,96.300003,91.660500,52161500
13,2016-01-22,98.629997,101.459999,98.370003,101.419998,96.533836,65800500
14,2016-01-25,101.519997,101.529999,99.209999,99.440002,94.649239,51794500
15,2016-01-26,99.930000,100.879997,98.070000,99.989998,95.172729,75077000
16,2016-01-27,96.040001,96.629997,93.339996,93.419998,88.919250,133369700
17,2016-01-28,93.790001,94.519997,92.389999,94.089996,89.556976,55678800
18,2016-01-29,94.790001,97.339996,94.349998,97.339996,92.650391,64416500
19,2016-02-01,96.470001,96.709999,95.400002,96.430000,91.784241,40943500
20,2016-02-02,95.419998,96.040001,94.279999,94.480003,89.928192,37357200
21,2016-02-03,95.000000,96.839996,94.080002,96.349998,91.708099,45964300
22,2016-02-04,95.860001,97.330002,95.190002,96.599998,92.444969,46471700
23,2016-02-05,96.519997,96.919998,93.690002,94.019997,89.975929,46418100
24,2016-02-08,93.129997,95.699997,93.040001,95.010002,90.923355,54021400
25,2016-02-09,94.290001,95.940002,93.930000,94.989998,90.904213,44331200
26,2016-02-10,95.919998,96.349998,94.099998,94.269997,90.215187,42343600
27,2016-02-11,93.790001,94.720001,92.589996,93.699997,89.669716,50074700
28,2016-02-12,94.190002,94.500000,93.010002,93.989998,89.947243,40351400
29,2016-02-16,95.019997,96.849998,94.610001,96.639999,92.483246,49057900
30,2016-02-17,96.669998,98.209999,96.150002,98.120003,93.899597,44863200
31,2016-02-18,98.839996,98.889999,96.089996,96.260002,92.119606,39021000
32,2016-02-19,96.000000,96.760002,95.800003,96.040001,91.909050,35374200
33,2016-02-22,96.309998,96.900002,95.919998,96.879997,92.712921,34280800
34,2016-02-23,96.400002,96.500000,94.550003,94.690002,90.617134,31942600
35,2016-02-24,93.980003,96.379997,93.320000,96.099998,91.966469,36255700
36,2016-02-25,96.050003,96.760002,95.250000,96.760002,92.598099,27582700
37,2016-02-26,97.199997,98.019997,96.580002,96.910004,92.741638,28991100
38,2016-02-29,96.860001,98.230003,96.650002,96.690002,92.531113,35216300
39,2016-03-01,97.650002,100.769997,97.419998,100.529999,96.205925,50407100
40,2016-03-02,100.510002,100.889999,99.639999,100.750000,96.416466,33169600
41,2016-03-03,100.580002,101.709999,100.449997,101.500000,97.134209,36955700
42,2016-03-04,102.370003,103.750000,101.370003,103.010002,98.579269,46055100
43,2016-03-07,102.389999,102.830002,100.959999,101.870003,97.488304,35828900
44,2016-03-08,100.779999,101.760002,100.400002,101.029999,96.684410,31561900
45,2016-03-09,101.309998,101.580002,100.269997,101.120003,96.770554,27201700
46,2016-03-10,101.410004,102.239998,100.150002,101.169998,96.818390,33513600
47,2016-03-11,102.239998,102.279999,101.500000,102.260002,97.861526,27408200
48,2016-03-14,101.910004,102.910004,101.779999,102.519997,98.110329,25076100
49,2016-03-15,103.959999,105.180000,103.849998,104.580002,100.081726,40067700

In [ ]:
sliced_2017 = df_2017.iloc[0:50]
sliced_2017

In [64]:
close_volume_2017 = np.array(sliced_2017[["Close", "Volume"]])
close_volume_2017

array([[1.16150002e+02, 2.87819000e+07],
       [1.16019997e+02, 2.11181000e+07],
       [1.16610001e+02, 2.21936000e+07],
       [1.17910004e+02, 3.17519000e+07],
       [1.18989998e+02, 3.35619000e+07],
       [1.19110001e+02, 2.44621000e+07],
       [1.19750000e+02, 2.75886000e+07],
       [1.19250000e+02, 2.70862000e+07],
       [1.19040001e+02, 2.61119000e+07],
       [1.20000000e+02, 3.44398000e+07],
       [1.19989998e+02, 2.37130000e+07],
       [1.19779999e+02, 2.55973000e+07],
       [1.20000000e+02, 3.25979000e+07],
       [1.20080002e+02, 2.20502000e+07],
       [1.19970001e+02, 2.32110000e+07],
       [1.21879997e+02, 3.23776000e+07],
       [1.21940002e+02, 2.63376000e+07],
       [1.21949997e+02, 2.05629000e+07],
       [1.21629997e+02, 3.03775000e+07],
       [1.21349998e+02, 4.92010000e+07],
       [1.28750000e+02, 1.11985000e+08],
       [1.28529999e+02, 3.37104000e+07],
       [1.29080002e+02, 2.45073000e+07],
       [1.30289993e+02, 2.68459000e+07],
       [1.31529999e+02, 3.81838000e+07],
       [1.32039993e+02, 2.30041000e+07],
       [1.32419998e+02, 2.83499000e+07],
       [1.32119995e+02, 2.00655000e+07],
       [1.33289993e+02, 2.30354000e+07],
       [1.35020004e+02, 3.32262000e+07],
       [1.35509995e+02, 3.56231000e+07],
       [1.35350006e+02, 2.25846000e+07],
       [1.35720001e+02, 2.21982000e+07],
       [1.36699997e+02, 2.45072000e+07],
       [1.37110001e+02, 2.08369000e+07],
       [1.36529999e+02, 2.07882000e+07],
       [1.36660004e+02, 2.17766000e+07],
       [1.36929993e+02, 2.02574000e+07],
       [1.36990005e+02, 2.34829000e+07],
       [1.39789993e+02, 3.64146000e+07],
       [1.38960007e+02, 2.62110000e+07],
       [1.39779999e+02, 2.11081000e+07],
       [1.39339996e+02, 2.17500000e+07],
       [1.39520004e+02, 1.74463000e+07],
       [1.39000000e+02, 1.87072000e+07],
       [1.38679993e+02, 2.21559000e+07],
       [1.39139999e+02, 1.96128000e+07],
       [1.39199997e+02, 1.74217000e+07],
       [1.38990005e+02, 1.53091000e+07],
       [1.40460007e+02, 2.56918000e+07]])

In [67]:
close_volume_2016 = np.array(sliced_2016[["Close", "Volume"]])
close_volume_2016

array([[1.05349998e+02, 6.76494000e+07],
       [1.02709999e+02, 5.57910000e+07],
       [1.00699997e+02, 6.84574000e+07],
       [9.64499970e+01, 8.10944000e+07],
       [9.69599990e+01, 7.07980000e+07],
       [9.85299990e+01, 4.97394000e+07],
       [9.99599990e+01, 4.91542000e+07],
       [9.73899990e+01, 6.24396000e+07],
       [9.95199970e+01, 6.31701000e+07],
       [9.71299970e+01, 7.90100000e+07],
       [9.66600040e+01, 5.30877000e+07],
       [9.67900010e+01, 7.23344000e+07],
       [9.63000030e+01, 5.21615000e+07],
       [1.01419998e+02, 6.58005000e+07],
       [9.94400020e+01, 5.17945000e+07],
       [9.99899980e+01, 7.50770000e+07],
       [9.34199980e+01, 1.33369700e+08],
       [9.40899960e+01, 5.56788000e+07],
       [9.73399960e+01, 6.44165000e+07],
       [9.64300000e+01, 4.09435000e+07],
       [9.44800030e+01, 3.73572000e+07],
       [9.63499980e+01, 4.59643000e+07],
       [9.65999980e+01, 4.64717000e+07],
       [9.40199970e+01, 4.64181000e+07],
       [9.50100020e+01, 5.40214000e+07],
       [9.49899980e+01, 4.43312000e+07],
       [9.42699970e+01, 4.23436000e+07],
       [9.36999970e+01, 5.00747000e+07],
       [9.39899980e+01, 4.03514000e+07],
       [9.66399990e+01, 4.90579000e+07],
       [9.81200030e+01, 4.48632000e+07],
       [9.62600020e+01, 3.90210000e+07],
       [9.60400010e+01, 3.53742000e+07],
       [9.68799970e+01, 3.42808000e+07],
       [9.46900020e+01, 3.19426000e+07],
       [9.60999980e+01, 3.62557000e+07],
       [9.67600020e+01, 2.75827000e+07],
       [9.69100040e+01, 2.89911000e+07],
       [9.66900020e+01, 3.52163000e+07],
       [1.00529999e+02, 5.04071000e+07],
       [1.00750000e+02, 3.31696000e+07],
       [1.01500000e+02, 3.69557000e+07],
       [1.03010002e+02, 4.60551000e+07],
       [1.01870003e+02, 3.58289000e+07],
       [1.01029999e+02, 3.15619000e+07],
       [1.01120003e+02, 2.72017000e+07],
       [1.01169998e+02, 3.35136000e+07],
       [1.02260002e+02, 2.74082000e+07],
       [1.02519997e+02, 2.50761000e+07],
       [1.04580002e+02, 4.00677000e+07]])

### Question 1

In [68]:
sum_2016 = close_volume_2016.sum(axis=1)
sum_2016

array([6.76495053e+07, 5.57911027e+07, 6.84575007e+07, 8.10944964e+07,
       7.07980970e+07, 4.97394985e+07, 4.91543000e+07, 6.24396974e+07,
       6.31701995e+07, 7.90100971e+07, 5.30877967e+07, 7.23344968e+07,
       5.21615963e+07, 6.58006014e+07, 5.17945994e+07, 7.50771000e+07,
       1.33369793e+08, 5.56788941e+07, 6.44165973e+07, 4.09435964e+07,
       3.73572945e+07, 4.59643963e+07, 4.64717966e+07, 4.64181940e+07,
       5.40214950e+07, 4.43312950e+07, 4.23436943e+07, 5.00747937e+07,
       4.03514940e+07, 4.90579966e+07, 4.48632981e+07, 3.90210963e+07,
       3.53742960e+07, 3.42808969e+07, 3.19426947e+07, 3.62557961e+07,
       2.75827968e+07, 2.89911969e+07, 3.52163967e+07, 5.04072005e+07,
       3.31697008e+07, 3.69558015e+07, 4.60552030e+07, 3.58290019e+07,
       3.15620010e+07, 2.72018011e+07, 3.35137012e+07, 2.74083023e+07,
       2.50762025e+07, 4.00678046e+07])

In [76]:
sum_2017 = close_volume_2017.sum(axis=1)
sum_2017

array([2.87820162e+07, 2.11182160e+07, 2.21937166e+07, 3.17520179e+07,
       3.35620190e+07, 2.44622191e+07, 2.75887198e+07, 2.70863192e+07,
       2.61120190e+07, 3.44399200e+07, 2.37131200e+07, 2.55974198e+07,
       3.25980200e+07, 2.20503201e+07, 2.32111200e+07, 3.23777219e+07,
       2.63377219e+07, 2.05630219e+07, 3.03776216e+07, 4.92011213e+07,
       1.11985129e+08, 3.37105285e+07, 2.45074291e+07, 2.68460303e+07,
       3.81839315e+07, 2.30042320e+07, 2.83500324e+07, 2.00656321e+07,
       2.30355333e+07, 3.32263350e+07, 3.56232355e+07, 2.25847354e+07,
       2.21983357e+07, 2.45073367e+07, 2.08370371e+07, 2.07883365e+07,
       2.17767367e+07, 2.02575369e+07, 2.34830370e+07, 3.64147398e+07,
       2.62111390e+07, 2.11082398e+07, 2.17501393e+07, 1.74464395e+07,
       1.87073390e+07, 2.21560387e+07, 1.96129391e+07, 1.74218392e+07,
       1.53092390e+07, 2.56919405e+07])

In [89]:
change_in_volume = close_volume_2017[:, 1] - close_volume_2016[:, 1]
change_in_volume

array([-3.886750e+07, -3.467290e+07, -4.626380e+07, -4.934250e+07,
       -3.723610e+07, -2.527730e+07, -2.156560e+07, -3.535340e+07,
       -3.705820e+07, -4.457020e+07, -2.937470e+07, -4.673710e+07,
       -1.956360e+07, -4.375030e+07, -2.858350e+07, -4.269940e+07,
       -1.070321e+08, -3.511590e+07, -3.403900e+07,  8.257500e+06,
        7.462780e+07, -1.225390e+07, -2.196440e+07, -1.957220e+07,
       -1.583760e+07, -2.132710e+07, -1.399370e+07, -3.000920e+07,
       -1.731600e+07, -1.583170e+07, -9.240100e+06, -1.643640e+07,
       -1.317600e+07, -9.773600e+06, -1.110570e+07, -1.546750e+07,
       -5.806100e+06, -8.733700e+06, -1.173340e+07, -1.399250e+07,
       -6.958600e+06, -1.584760e+07, -2.430510e+07, -1.838260e+07,
       -1.285470e+07, -5.045800e+06, -1.390080e+07, -9.986500e+06,
       -9.767000e+06, -1.437590e+07])

In [92]:
change_in_traded_volume = change_in_volume.sum(axis=0)
change_in_traded_volume

-1089213200.0

### Question 2

In [90]:
change = close_volume_2017 - close_volume_2016
change

array([[ 1.0800004e+01, -3.8867500e+07],
       [ 1.3309998e+01, -3.4672900e+07],
       [ 1.5910004e+01, -4.6263800e+07],
       [ 2.1460007e+01, -4.9342500e+07],
       [ 2.2029999e+01, -3.7236100e+07],
       [ 2.0580002e+01, -2.5277300e+07],
       [ 1.9790001e+01, -2.1565600e+07],
       [ 2.1860001e+01, -3.5353400e+07],
       [ 1.9520004e+01, -3.7058200e+07],
       [ 2.2870003e+01, -4.4570200e+07],
       [ 2.3329994e+01, -2.9374700e+07],
       [ 2.2989998e+01, -4.6737100e+07],
       [ 2.3699997e+01, -1.9563600e+07],
       [ 1.8660004e+01, -4.3750300e+07],
       [ 2.0529999e+01, -2.8583500e+07],
       [ 2.1889999e+01, -4.2699400e+07],
       [ 2.8520004e+01, -1.0703210e+08],
       [ 2.7860001e+01, -3.5115900e+07],
       [ 2.4290001e+01, -3.4039000e+07],
       [ 2.4919998e+01,  8.2575000e+06],
       [ 3.4269997e+01,  7.4627800e+07],
       [ 3.2180001e+01, -1.2253900e+07],
       [ 3.2480004e+01, -2.1964400e+07],
       [ 3.6269996e+01, -1.9572200e+07],
       [ 3.6519997e+01, -1.5837600e+07],
       [ 3.7049995e+01, -2.1327100e+07],
       [ 3.8150001e+01, -1.3993700e+07],
       [ 3.8419998e+01, -3.0009200e+07],
       [ 3.9299995e+01, -1.7316000e+07],
       [ 3.8380005e+01, -1.5831700e+07],
       [ 3.7389992e+01, -9.2401000e+06],
       [ 3.9090004e+01, -1.6436400e+07],
       [ 3.9680000e+01, -1.3176000e+07],
       [ 3.9820000e+01, -9.7736000e+06],
       [ 4.2419999e+01, -1.1105700e+07],
       [ 4.0430001e+01, -1.5467500e+07],
       [ 3.9900002e+01, -5.8061000e+06],
       [ 4.0019989e+01, -8.7337000e+06],
       [ 4.0300003e+01, -1.1733400e+07],
       [ 3.9259994e+01, -1.3992500e+07],
       [ 3.8210007e+01, -6.9586000e+06],
       [ 3.8279999e+01, -1.5847600e+07],
       [ 3.6329994e+01, -2.4305100e+07],
       [ 3.7650001e+01, -1.8382600e+07],
       [ 3.7970001e+01, -1.2854700e+07],
       [ 3.7559990e+01, -5.0458000e+06],
       [ 3.7970001e+01, -1.3900800e+07],
       [ 3.6939995e+01, -9.9865000e+06],
       [ 3.6470008e+01, -9.7670000e+06],
       [ 3.5880005e+01, -1.4375900e+07]])

In [88]:
sum_change = change.sum(axis=1)
sum_change

array([-3.88674892e+07, -3.46728867e+07, -4.62637841e+07, -4.93424785e+07,
       -3.72360780e+07, -2.52772794e+07, -2.15655802e+07, -3.53533781e+07,
       -3.70581805e+07, -4.45701771e+07, -2.93746767e+07, -4.67370770e+07,
       -1.95635763e+07, -4.37502813e+07, -2.85834795e+07, -4.26993781e+07,
       -1.07032071e+08, -3.51158721e+07, -3.40389757e+07,  8.25752492e+06,
        7.46278343e+07, -1.22538678e+07, -2.19643675e+07, -1.95721637e+07,
       -1.58375635e+07, -2.13270630e+07, -1.39936618e+07, -3.00091616e+07,
       -1.73159607e+07, -1.58316616e+07, -9.24006261e+06, -1.64363609e+07,
       -1.31759603e+07, -9.77356018e+06, -1.11056576e+07, -1.54674596e+07,
       -5.80606010e+06, -8.73365998e+06, -1.17333597e+07, -1.39924607e+07,
       -6.95856179e+06, -1.58475617e+07, -2.43050637e+07, -1.83825623e+07,
       -1.28546620e+07, -5.04576244e+06, -1.39007620e+07, -9.98646306e+06,
       -9.76696353e+06, -1.43758641e+07])

In [95]:
sum_change_volume = sum_change.sum(axis=0)
sum_change_volume

-1089211640.5900083

### Question 3

In [101]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
# np.set_printoptions()

print(change)

[[ 10.80 -38867500.00]
 [ 13.31 -34672900.00]
 [ 15.91 -46263800.00]
 [ 21.46 -49342500.00]
 [ 22.03 -37236100.00]
 [ 20.58 -25277300.00]
 [ 19.79 -21565600.00]
 [ 21.86 -35353400.00]
 [ 19.52 -37058200.00]
 [ 22.87 -44570200.00]
 [ 23.33 -29374700.00]
 [ 22.99 -46737100.00]
 [ 23.70 -19563600.00]
 [ 18.66 -43750300.00]
 [ 20.53 -28583500.00]
 [ 21.89 -42699400.00]
 [ 28.52 -107032100.00]
 [ 27.86 -35115900.00]
 [ 24.29 -34039000.00]
 [ 24.92  8257500.00]
 [ 34.27  74627800.00]
 [ 32.18 -12253900.00]
 [ 32.48 -21964400.00]
 [ 36.27 -19572200.00]
 [ 36.52 -15837600.00]
 [ 37.05 -21327100.00]
 [ 38.15 -13993700.00]
 [ 38.42 -30009200.00]
 [ 39.30 -17316000.00]
 [ 38.38 -15831700.00]
 [ 37.39 -9240100.00]
 [ 39.09 -16436400.00]
 [ 39.68 -13176000.00]
 [ 39.82 -9773600.00]
 [ 42.42 -11105700.00]
 [ 40.43 -15467500.00]
 [ 39.90 -5806100.00]
 [ 40.02 -8733700.00]
 [ 40.30 -11733400.00]
 [ 39.26 -13992500.00]
 [ 38.21 -6958600.00]
 [ 38.28 -15847600.00]
 [ 36.33 -24305100.00]
 [ 37.65 -18382600.00]
 [ 37.97 -12854700.00]
 [ 37.56 -5045800.00]
 [ 37.97 -13900800.00]
 [ 36.94 -9986500.00]
 [ 36.47 -9767000.00]
 [ 35.88 -14375900.00]]

### Question 4

In [105]:
combined_years = np.concatenate( (np.array(sliced_2016), np.array(sliced_2017)), axis=0 )

combined_years

array([['2016-01-04', 102.610001, 105.370003, 102.0, 105.349998,
        100.274513, 67649400],
       ['2016-01-05', 105.75, 105.849998, 102.410004, 102.709999,
        97.761681, 55791000],
       ['2016-01-06', 100.559998, 102.370003, 99.870003, 100.699997,
        95.848511, 68457400],
       ['2016-01-07', 98.68, 100.129997, 96.43, 96.449997, 91.803276,
        81094400],
       ['2016-01-08', 98.550003, 99.110001, 96.760002, 96.959999,
        92.288696, 70798000],
       ['2016-01-11', 98.970001, 99.059998, 97.339996, 98.529999,
        93.783073, 49739400],
       ['2016-01-12', 100.550003, 100.690002, 98.839996, 99.959999,
        95.144165, 49154200],
       ['2016-01-13', 100.32, 101.190002, 97.300003, 97.389999, 92.69799,
        62439600],
       ['2016-01-14', 97.959999, 100.480003, 95.739998, 99.519997,
        94.725372, 63170100],
       ['2016-01-15', 96.199997, 97.709999, 95.360001, 97.129997,
        92.450516, 79010000],
       ['2016-01-19', 98.410004, 98.650002, 95.5, 96.660004, 92.003166,
        53087700],
       ['2016-01-20', 95.099998, 98.190002, 93.419998, 96.790001,
        92.1269, 72334400],
       ['2016-01-21', 97.059998, 97.879997, 94.940002, 96.300003,
        91.6605, 52161500],
       ['2016-01-22', 98.629997, 101.459999, 98.370003, 101.419998,
        96.533836, 65800500],
       ['2016-01-25', 101.519997, 101.529999, 99.209999, 99.440002,
        94.649239, 51794500],
       ['2016-01-26', 99.93, 100.879997, 98.07, 99.989998, 95.172729,
        75077000],
       ['2016-01-27', 96.040001, 96.629997, 93.339996, 93.419998,
        88.91925, 133369700],
       ['2016-01-28', 93.790001, 94.519997, 92.389999, 94.089996,
        89.556976, 55678800],
       ['2016-01-29', 94.790001, 97.339996, 94.349998, 97.339996,
        92.650391, 64416500],
       ['2016-02-01', 96.470001, 96.709999, 95.400002, 96.43, 91.784241,
        40943500],
       ['2016-02-02', 95.419998, 96.040001, 94.279999, 94.480003,
        89.928192, 37357200],
       ['2016-02-03', 95.0, 96.839996, 94.080002, 96.349998, 91.708099,
        45964300],
       ['2016-02-04', 95.860001, 97.330002, 95.190002, 96.599998,
        92.444969, 46471700],
       ['2016-02-05', 96.519997, 96.919998, 93.690002, 94.019997,
        89.975929, 46418100],
       ['2016-02-08', 93.129997, 95.699997, 93.040001, 95.010002,
        90.923355, 54021400],
       ['2016-02-09', 94.290001, 95.940002, 93.93, 94.989998, 90.904213,
        44331200],
       ['2016-02-10', 95.919998, 96.349998, 94.099998, 94.269997,
        90.215187, 42343600],
       ['2016-02-11', 93.790001, 94.720001, 92.589996, 93.699997,
        89.669716, 50074700],
       ['2016-02-12', 94.190002, 94.5, 93.010002, 93.989998, 89.947243,
        40351400],
       ['2016-02-16', 95.019997, 96.849998, 94.610001, 96.639999,
        92.483246, 49057900],
       ['2016-02-17', 96.669998, 98.209999, 96.150002, 98.120003,
        93.899597, 44863200],
       ['2016-02-18', 98.839996, 98.889999, 96.089996, 96.260002,
        92.119606, 39021000],
       ['2016-02-19', 96.0, 96.760002, 95.800003, 96.040001, 91.90905,
        35374200],
       ['2016-02-22', 96.309998, 96.900002, 95.919998, 96.879997,
        92.712921, 34280800],
       ['2016-02-23', 96.400002, 96.5, 94.550003, 94.690002, 90.617134,
        31942600],
       ['2016-02-24', 93.980003, 96.379997, 93.32, 96.099998, 91.966469,
        36255700],
       ['2016-02-25', 96.050003, 96.760002, 95.25, 96.760002, 92.598099,
        27582700],
       ['2016-02-26', 97.199997, 98.019997, 96.580002, 96.910004,
        92.741638, 28991100],
       ['2016-02-29', 96.860001, 98.230003, 96.650002, 96.690002,
        92.531113, 35216300],
       ['2016-03-01', 97.650002, 100.769997, 97.419998, 100.529999,
        96.205925, 50407100],
       ['2016-03-02', 100.510002, 100.889999, 99.639999, 100.75,
        96.416466, 33169600],
       ['2016-03-03', 100.580002, 101.709999, 100.449997, 101.5,
        97.134209, 36955700],
       ['2016-03-04', 102.370003, 103.75, 101.370003, 103.010002,
        98.579269, 46055100],
       ['2016-03-07', 102.389999, 102.830002, 100.959999, 101.870003,
        97.488304, 35828900],
       ['2016-03-08', 100.779999, 101.760002, 100.400002, 101.029999,
        96.68441, 31561900],
       ['2016-03-09', 101.309998, 101.580002, 100.269997, 101.120003,
        96.770554, 27201700],
       ['2016-03-10', 101.410004, 102.239998, 100.150002, 101.169998,
        96.81839, 33513600],
       ['2016-03-11', 102.239998, 102.279999, 101.5, 102.260002,
        97.861526, 27408200],
       ['2016-03-14', 101.910004, 102.910004, 101.779999, 102.519997,
        98.110329, 25076100],
       ['2016-03-15', 103.959999, 105.18, 103.849998, 104.580002,
        100.081726, 40067700],
       ['2017-01-03', 115.800003, 116.330002, 114.760002, 116.150002,
        113.013916, 28781900],
       ['2017-01-04', 115.849998, 116.510002, 115.75, 116.019997,
        112.887413, 21118100],
       ['2017-01-05', 115.919998, 116.860001, 115.809998, 116.610001,
        113.461502, 22193600],
       ['2017-01-06', 116.779999, 118.160004, 116.470001, 117.910004,
        114.726402, 31751900],
       ['2017-01-09', 117.949997, 119.43, 117.940002, 118.989998,
        115.777237, 33561900],
       ['2017-01-10', 118.769997, 119.379997, 118.300003, 119.110001,
        115.893997, 24462100],
       ['2017-01-11', 118.739998, 119.93, 118.599998, 119.75, 116.516708,
        27588600],
       ['2017-01-12', 118.900002, 119.300003, 118.209999, 119.25,
        116.030212, 27086200],
       ['2017-01-13', 119.110001, 119.620003, 118.809998, 119.040001,
        115.825882, 26111900],
       ['2017-01-17', 118.339996, 120.239998, 118.220001, 120.0,
        116.759972, 34439800],
       ['2017-01-18', 120.0, 120.5, 119.709999, 119.989998, 116.750229,
        23713000],
       ['2017-01-19', 119.400002, 120.089996, 119.370003, 119.779999,
        116.545898, 25597300],
       ['2017-01-20', 120.449997, 120.449997, 119.730003, 120.0,
        116.759972, 32597900],
       ['2017-01-23', 120.0, 120.809998, 119.769997, 120.080002,
        116.837799, 22050200],
       ['2017-01-24', 119.550003, 120.099998, 119.5, 119.970001,
        116.730774, 23211000],
       ['2017-01-25', 120.419998, 122.099998, 120.279999, 121.879997,
        118.589195, 32377600],
       ['2017-01-26', 121.669998, 122.440002, 121.599998, 121.940002,
        118.647583, 26337600],
       ['2017-01-27', 122.139999, 122.349998, 121.599998, 121.949997,
        118.657303, 20562900],
       ['2017-01-30', 120.93, 121.629997, 120.660004, 121.629997,
        118.345947, 30377500],
       ['2017-01-31', 121.150002, 121.389999, 120.620003, 121.349998,
        118.073517, 49201000],
       ['2017-02-01', 127.029999, 130.490005, 127.010002, 128.75,
        125.273705, 111985000],
       ['2017-02-02', 127.980003, 129.389999, 127.779999, 128.529999,
        125.059654, 33710400],
       ['2017-02-03', 128.309998, 129.190002, 128.160004, 129.080002,
        125.594803, 24507300],
       ['2017-02-06', 129.130005, 130.5, 128.899994, 130.289993,
        126.772125, 26845900],
       ['2017-02-07', 130.539993, 132.089996, 130.449997, 131.529999,
        127.97863, 38183800],
       ['2017-02-08', 131.350006, 132.220001, 131.220001, 132.039993,
        128.474869, 23004100],
       ['2017-02-09', 131.649994, 132.449997, 131.119995, 132.419998,
        129.403229, 28349900],
       ['2017-02-10', 132.460007, 132.940002, 132.050003, 132.119995,
        129.110077, 20065500],
       ['2017-02-13', 133.080002, 133.820007, 132.75, 133.289993,
        130.253418, 23035400],
       ['2017-02-14', 133.470001, 135.089996, 133.25, 135.020004,
        131.944016, 33226200],
       ['2017-02-15', 135.520004, 136.270004, 134.619995, 135.509995,
        132.422836, 35623100],
       ['2017-02-16', 135.669998, 135.899994, 134.839996, 135.350006,
        132.266495, 22584600],
       ['2017-02-17', 135.100006, 135.830002, 135.100006, 135.720001,
        132.628067, 22198200],
       ['2017-02-21', 136.229996, 136.75, 135.979996, 136.699997,
        133.585724, 24507200],
       ['2017-02-22', 136.429993, 137.119995, 136.110001, 137.110001,
        133.986389, 20836900],
       ['2017-02-23', 137.380005, 137.479996, 136.300003, 136.529999,
        133.419601, 20788200],
       ['2017-02-24', 135.910004, 136.660004, 135.279999, 136.660004,
        133.546661, 21776600],
       ['2017-02-27', 137.139999, 137.440002, 136.279999, 136.929993,
        133.810471, 20257400],
       ['2017-02-28', 137.080002, 137.440002, 136.699997, 136.990005,
        133.86911, 23482900],
       ['2017-03-01', 137.889999, 140.149994, 137.600006, 139.789993,
        136.605331, 36414600],
       ['2017-03-02', 140.0, 140.279999, 138.759995, 138.960007,
        135.79425, 26211000],
       ['2017-03-03', 138.779999, 139.830002, 138.589996, 139.779999,
        136.595566, 21108100],
       ['2017-03-06', 139.369995, 139.770004, 138.600006, 139.339996,
        136.165573, 21750000],
       ['2017-03-07', 139.059998, 139.979996, 138.789993, 139.520004,
        136.341476, 17446300],
       ['2017-03-08', 138.949997, 139.800003, 138.820007, 139.0,
        135.833344, 18707200],
       ['2017-03-09', 138.740005, 138.789993, 137.050003, 138.679993,
        135.520599, 22155900],
       ['2017-03-10', 139.25, 139.360001, 138.639999, 139.139999,
        135.970139, 19612800],
       ['2017-03-13', 138.850006, 139.429993, 138.820007, 139.199997,
        136.028748, 17421700],
       ['2017-03-14', 139.300003, 139.649994, 138.839996, 138.990005,
        135.823547, 15309100],
       ['2017-03-15', 139.410004, 140.75, 139.029999, 140.460007,
        137.260071, 25691800]], dtype=object)